# Generated by Django 5.0.6 on 2024-07-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminside', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.CharField(default='', max_length=255),
        ),
    ]
