# Generated by Django 5.0.6 on 2024-07-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminside', '0002_category_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_teends_or_just_arived',
            field=models.BooleanField(default=True),
        ),
    ]
