# Generated by Django 5.0.6 on 2024-07-31 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminside', '0003_product_is_teends_or_just_arived'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('user_image', models.ImageField(upload_to='User')),
                ('pincode', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('land_mark', models.CharField(max_length=255)),
            ],
        ),
    ]
