# Generated by Django 5.0.6 on 2024-08-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminside', '0005_userprofile_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(default='', max_length=100),
        ),
    ]
