# Generated by Django 5.0.6 on 2024-09-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminside', '0009_contactus_is_replied_contactus_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(default='', upload_to='banner')),
                ('is_show', models.BooleanField(default='False')),
            ],
        ),
    ]
