# Generated by Django 5.0.6 on 2024-09-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminside', '0010_addbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_image', models.ImageField(default='', upload_to='offer')),
                ('offer_description', models.CharField(max_length=225)),
                ('offer_title', models.CharField(max_length=225)),
                ('is_showing', models.BooleanField(default='False')),
            ],
        ),
    ]
