# Generated by Django 5.0.6 on 2024-09-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminside', '0012_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='', max_length=255),
        ),
    ]
