# Generated by Django 5.0.6 on 2024-09-06 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminside', '0013_profile_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
