# Generated by Django 5.0.6 on 2024-09-19 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminside', '0015_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Product_id',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='User_id',
            new_name='user_id',
        ),
    ]
