# Generated by Django 5.0.6 on 2024-09-19 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminside', '0016_rename_product_id_cart_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Date_added',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='Quantity',
            new_name='quantity',
        ),
    ]
