# Generated by Django 5.0.6 on 2024-09-28 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminside', '0018_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='product_id',
        ),
    ]
